#spring:
#  profiles:
#    active: mysql-dev

server:
  port: 8081
spring:
  application:
    name: pdms-consumer
  devtools:
      restart:
        enabled: false
  datasource:
        url: jdbc:mysql://localhost:3306/lenos?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  redis:
    host: localhost
    port: 6379

mybatis:
    type-aliases-package: com.len.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true
    configuration:
      map-underscore-to-camel-case: true

mapper:
    mappers:
        - com.len.base.BaseMapper
        - tk.mybatis.mapper.common.Mapper
    not-empty: true
    identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

lenosp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/lenosp-consumer-log.log
  level:
    com.len.mapper: debug

dataType: mysql

redis:
  prefix: len_

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    logger: slf4j
  scan:
    base-packages: com.len
  consumer:
    filter: dubboConsumerContextFilter


